erDiagram
    song {
        int id
        string title
        int duration
        string file_path
        string image_path
    }

    song_artist {
        int song_id
        int artist_id
    }

    artist {
        int id
        string name
    }

    song_album {
        int song_id
        int album_id
    }

    album {
        int id
        string title
    }

    playlist {
        int id
        string title
        string image_path
        int total_count
        timestamps total_duration
    }

    playlist_song {
        int sort_index
        int song_id
        int playlist_id
    }

    song ||--|{ song_artist : ""
    song_artist ||--|| artist : ""
    song ||--|{ song_album : ""
    song_album ||--|| album : ""
    song ||--|{ playlist_song : ""
    playlist_song }|--|| playlist : ""
